export const blankBook: Book = {
    authors: [''],
    currentPage: 0,
    id: 0,
    pageCount: 0,
    categories: [''],
    description: '',
    endDate: '',
    imageLinks: {
        extraLarge: '',
        large: '',
        medium: '',
        small: '',
        smallThumbnail: '',
        thumbnail: '',
    },
    isbn: '',
    language: '',
    maturityRating: 'NOT_MATURE',
    previewLink: '',
    printedPageCount: 0,
    publishedDate: '',
    publisher: '',
    rating: 0,
    startDate: '',
    state: 'READ_LATER',
    subtitle: '',
    title: '',
};
