export const cryptoList: CryptoDetails[] = [
  {
    name: 'Bitcoin',
    code: 'BTC',
    address: 'bc1qv8etvy94m5jh7f6lexnnr4j9k8v78vs5cekp86',
    icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/bitcoin.png'),
  },
  {
    name: 'Ethereum',
    code: 'ETH',
    address: '0x45768dd038b2889D38eEd55Afd462B7275D45855',
    icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/ethereum.png'),
  },
  {
    name: 'Binance Coin',
    code: 'BNB',
    address: '0x45768dd038b2889D38eEd55Afd462B7275D45855',
    icon: 'https://cryptologos.cc/logos/binance-coin-bnb-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/bnb.png'),
  },
  {
    name: 'Polygon',
    code: 'MATIC',
    address: '0x45768dd038b2889D38eEd55Afd462B7275D45855',
    icon: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/polygon.png'),
  },
  {
    name: 'Toncoin',
    code: 'TON',
    address: 'UQBb4xTfCi-_O9dcqCLDD_ZEiumT3N7uA4FN7YL7gOeDmTdA',
    icon: 'https://cryptologos.cc/logos/toncoin-ton-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/ton.png'),
  },
  {
    name: 'TRON',
    code: 'TRX',
    address: 'TTMkHz2BSTRmrqbTVMbjyRPzRUoPgib5am',
    icon: 'https://cryptologos.cc/logos/tron-trx-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/tron.png'),
  },
  {
    name: 'Dash',
    code: 'DASH',
    address: 'XoaRXS13dXeAABFzhyE1MivTJVdYKcuoGn',
    icon: 'https://cryptologos.cc/logos/dash-dash-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/dash.png'),
  },
  {
    name: 'Litecoin',
    code: 'LTC',
    address: 'ltc1qss4pap6szv709hz8v9hkazv658n3cv8f58w6zd',
    icon: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/litecoin.png'),
  },
  {
    name: 'Solana',
    code: 'SOL',
    address: '96mqHLrAwDR57ZAV1foWp2AWAgecpQRmMqZuSENy3mZD',
    icon: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    offIcon: require('@/assets/images/cryptoIcons/solana.png'),
  },
];
