[
    {
        author: 'Agatha Christie',
        currentPage: 24,
        endDate: 0,
        googleBooksLink: 'http://books.google.co.in/books?id=8IFWMwAACAAJ&dq=peril%2Bat%2Bend%2Bhouse&hl=&source=gbs_api',
        pageCount: 160,
        publishedDate: '2010',
        rating: 0,
        startDate: 1686943030802,
        state: 'READING',
        subTitle: '',
        summary: "Hercule Poirot's holiday on the Cornish coast is rudely interrupted when he runs into a real-life damsel in distress. Young Nick Buckley, owner of the eerie and imposing End House, has already survived three attempts on her life, and even now is being shot at by an unseen gunman. Deciding to protect her, Poirot finds himself trying to solve a murder that hasn't happened yet.",
        title: 'Peril at End House',
        wishlistDate: 0,
    },
    {
        author: 'Agatha Christie',
        currentPage: 149,
        endDate: 1686942768923,
        googleBooksLink: 'http://books.google.co.in/books?id=M5iXzwEACAAJ&dq=big%2Bfour&hl=&source=gbs_api',
        id: 26,
        isbn: '9781420981148',
        labels: [],
        language: 'en',
        pageCount: 149,
        position: 0,
        publishedDate: '2023-01-02',
        rating: 0,
        startDate: 1686805128063,
        state: 'READ',
        subTitle: '',
        summary:
            "First published in 1927, \"The Big Four\" is the fifth mystery by Agatha Christie to feature her most famous character, the brilliant detective Hercule Poirot. Widely regarded as one of Christie's most ambitious and complicated mysteries, the story takes place over a year as Poirot is determined to find out who is responsible for the death of a secretive and sickly man who mysteriously appears in the detective's apartment one evening. Based upon the dead man's cryptic clues, Poirot soon realizes that he is up against his most challenging foe yet: a secretive and anonymous group of four powerful figures who control crime around the world. Poirot's investigation takes him all over England, threatening both his life and that of his brother, as he attempts to reveal the identities of these shadowy and dangerous figures. Many of Christie's most popular and entertaining characters aid Poirot in his epic quest, including the resourceful Major Hastings and the enigmatic Countess Vera Rossakoff. Full of fascinating characters, deadly villains, and an international criminal conspiracy, fans of mystery and suspense will be drawn into this intriguing tale of criminal espionage. This edition is printed on premium acid-free paper.",
        thumbnailAddress: 'http://books.google.com/books/content?id=M5iXzwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The Big Four',
        wishlistDate: 1686805124979,
    },
    {
        author: 'Agatha Christie',
        currentPage: 170,
        endDate: 1686737793071,
        googleBooksLink: 'http://books.google.co.in/books?id=swmDzQEACAAJ&dq=murder%2Bon%2Bthe%2Blinks&hl=&source=gbs_api',
        id: 25,
        isbn: '9798643396956',
        labels: [],
        language: 'en',
        pageCount: 170,
        position: 0,
        publishedDate: '2020-05-05',
        rating: 0,
        startDate: 1686447817381,
        state: 'READ',
        subTitle: 'A Hercule Poirot Mystery',
        summary:
            "When Hercule Poirot and his sidekick Arthur Hastings arrive in the French village of Merlinville-sur-Mer to meet their client Paul Renauld they learn from Paris police that he has been found that morning stabbed in the back with a letter opener and left in a newly dug grave adjacent to a local golf course. Among the plausible suspects are Renauld's wife Eloise, his son Jack, an unknown visitor of the previous day, Renauld's immediate neighbor Madame Daubreuil, and the mysterious \"Cinderella\" of Hasting's recent acquaintance-all of whom Poirot has reason to suspect. Poirot's powers of investigation ultimately triumph over the wiles of an assailant whose misdirection and motives are nearly-but not quite-impossible to spot. Contains a character key, a detailed biography, and an illustrated list of notable Poirot portrayals. Agatha Christie is the \"Queen of Mystery\" and the world's best-selling mystery writer. Over the course of more than half a century she wrote eighty crime novels and short story collections, nineteen plays, and several poetry collections. Her books have sold more than a billion copies in the English language and another billion in a hundred other languages. Agatha Christie died in 1976.",
        thumbnailAddress: 'http://books.google.com/books/content?id=swmDzQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The Murder on the Links',
        wishlistDate: 1686445710478,
    },
    {
        author: 'Agatha Christie',
        currentPage: 170,
        endDate: 1686333563811,
        googleBooksLink: 'http://books.google.co.in/books?id=x67ZswEACAAJ&dq=mysterious%2Baffairs&hl=&source=gbs_api',
        id: 24,
        isbn: '9780062984630',
        labels: [],
        language: 'en',
        pageCount: 170,
        position: 0,
        publishedDate: '2020-01-14',
        rating: 0,
        startDate: 1685936640800,
        state: 'READ',
        subTitle: 'A Hercule Poirot Mystery',
        summary:
            '"It\'s tempting to say that Agatha Christie is a genius and let it go at that, but the world\'s had plenty of geniuses. Agatha Christie is something special."--Lawrence Block, New York Times bestselling author In this official and fully restored edition, Hercule Poirot solves his first case in the Agatha Christie novel that started it all, now featuring a "missing chapter" and exclusive content from the Queen of Mystery. Who poisoned the wealthy Emily Inglethorp and how did the murderer penetrate and escape from her locked bedroom? Suspects abound in the quaint village of Styles St. Mary--from the heiress\'s fawning new husband to her two stepsons, her volatile housekeeper, and a pretty nurse who works in a hospital dispensary. With impeccable timing, and making his unforgettable debut, the brilliant Belgian detective Hercule Poirot is on the case. One of the best-loved classic mysteries of all time, The Mysterious Affair at Styles will continue to enchant old readers and introduce Agatha Christie\'s unique storytelling genius to a host of new readers.',
        thumbnailAddress: 'http://books.google.com/books/content?id=x67ZswEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The Mysterious Affair at Styles',
        wishlistDate: 0,
    },
    {
        author: 'Roberto Bolaño',
        currentPage: 182,
        endDate: 1685888275554,
        googleBooksLink: 'http://books.google.co.in/books?id=Mu6-SdS5N5MC&dq=skating%2Brink&hl=&source=gbs_api',
        id: 21,
        isbn: '9780811220590',
        labels: [],
        language: 'en',
        pageCount: 182,
        position: 0,
        publishedDate: '2011-02-28',
        rating: 0,
        startDate: 1685508676174,
        state: 'READ',
        subTitle: '',
        summary:
            'A phenomenally unusual three-way murder mystery. With a murder at its heart, Roberto Bolano’s The Skating Rink is, among other things, a crime novel. Murder seems to have exerted a fascination for the endlessly talented Bolano, who in his last interview, according to The Observer, “declared, in all apparent seriousness, that what he would most like to have been was a homicide detective.” Set in the seaside town of Z, north of Barcelona, The Skating Rink is told in short, suspenseful chapters by three male narrators, and revolves around a beautiful figure skating champion, Nuria Martí. A ruined mansion, knife-wielding women, political corruption, sex, and jealousy all appear in this atmospheric chronicle of a single summer season in a seaside town, with its vacationers, businessmen, immigrants, bureaucrats, social workers, and drifters.',
        thumbnailAddress: 'http://books.google.com/books/content?id=Mu6-SdS5N5MC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'The Skating Rink',
        wishlistDate: 0,
    },
    {
        author: 'Saradindu Bandyopadhyay',
        currentPage: 183,
        endDate: 1685507172842,
        googleBooksLink: 'https://play.google.com/store/books/details?id=PITaV9w83xwC&source=gbs_api',
        id: 20,
        isbn: '9788184756968',
        labels: [],
        language: 'en',
        pageCount: 183,
        position: 0,
        publishedDate: '2012-07-17',
        rating: 0,
        startDate: 1685344954891,
        state: 'READ',
        subTitle: '3 Byomkesh Bakshi Mysteries',
        summary:
            "Saradindu Bandyopadyay's immortal detective Byomkesh Bakshi has enjoyed immense popularity for several decades. From being a household name in the Calcutta of 1930s, when he first created, to a popular face on TV in the 1990s, Byomkesh along with his friend-cum-foil Ajit is perhaps the best-loved of India's literary detectives. This collection brings together three of his classic whodunnits. From a murder in a boarding house with too many suspects to a mystery with a supernatural twist, and then busting a black - marketeering ring in rural bengal, these stories take the super sleuth to different locales on his quest for truth, and bring out his ingenuity and astuteness. Translated into English for the first time by award-winning translator Arunava Sinha, the breathless pace and thrilling plots of these action-packed adventures will win Byomkesh a new genertion of admirers.",
        thumbnailAddress: 'http://books.google.com/books/content?id=PITaV9w83xwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'The Rhythm of Riddles',
        wishlistDate: 0,
    },
    { author: 'Emile Burns', currentPage: 0, endDate: 0, googleBooksLink: 'http://books.google.co.in/books?id=ZBhtAAAAIAAJ&dq=Emile%2Bburns&hl=&source=gbs_api', id: 19, isbn: '', labels: [], language: 'en', pageCount: 140, position: 0, publishedDate: '1957', rating: 0, startDate: 0, state: 'READ_LATER', subTitle: '', thumbnailAddress: 'http://books.google.com/books/content?id=ZBhtAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', title: 'What is Marxism?', wishlistDate: 1682811907790 },
    {
        author: 'Yukito Ayatsuji',
        currentPage: 284,
        endDate: 1685344926885,
        googleBooksLink: 'http://books.google.co.in/books?id=1GIrEAAAQBAJ&dq=decagon%2Bhouse&hl=&source=gbs_api',
        id: 18,
        isbn: '9781782276340',
        labels: [],
        language: 'en',
        pageCount: 284,
        position: 0,
        publishedDate: '2021-05-25',
        rating: 0,
        startDate: 1684979033101,
        state: 'READ',
        subTitle: '',
        summary:
            '"Ayatsuji\'s brilliant and richly atmospheric puzzle will appeal to fans of golden age whodunits... Every word counts, leading up to a jaw-dropping but logical reveal" — Publishers Weekly A hugely enjoyable, page-turning murder mystery sure to appeal to fans of Elly Griffiths, Anthony Horowitz, and Agatha Christie, with one of the best and most-satisfying conclusions you\'ll ever read. A classic in Japan, available in English for the first time. From The New York Times Book Review: "Read Yukito Ayatsuji’s landmark mystery, The Decagon House Murders, and discover a real depth of feeling beneath the fiendish foul play. Taking its cues from Agatha Christie’s locked-room classic And Then There Were None, the setup is this: The members of a university detective-fiction club, each nicknamed for a favorite crime writer (Poe, Carr, Orczy, Van Queen, Leroux and — yes — Christie), spend a week on remote Tsunojima Island, attracted to the place, and its eerie 10-sided house, because of a spate of murders that transpired the year before. That collective curiosity will, of course, be their undoing. As the students approach Tsunojima in a hired fishing boat, \'the sunlight shining down turned the rippling waves to silver. The island lay ahead of them, wrapped in a misty veil of dust,\' its sheer, dark cliffs rising straight out of the sea, accessible by one small inlet. There is no electricity on the island, and no telephones, either. A fresh round of violent deaths begins, and Ayatsuji’s skillful, furious pacing propels the narrative. As the students are picked off one by one, he weaves in the story of the mainland investigation of the earlier murders. This is a homage to Golden Age detective fiction, but it’s also unabashed entertainment."',
        thumbnailAddress: 'http://books.google.com/books/content?id=1GIrEAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The Decagon House Murders',
        wishlistDate: 0,
    },
    {
        author: 'Saradindu Bandyopadhyay',
        currentPage: 249,
        endDate: 1682999652406,
        googleBooksLink: 'https://play.google.com/store/books/details?id=eNGfBAAAQBAJ&source=gbs_api',
        id: 17,
        isbn: '9789351187912',
        labels: [],
        language: 'en',
        pageCount: 249,
        position: 0,
        publishedDate: '2000-10-14',
        rating: 0,
        startDate: 1682269811717,
        state: 'READ',
        subTitle: 'and other Byomkesh Bakshi Mysteries',
        summary:
            'Classic tales of crime detection featuring Byomkesh Bakshi, the master inquisitor Written long before Satyajit Ray’s Feluda series, Saradindu Bandyopadhyay’s Byomkesh Bakshi mysteries heralded a new era in Bengali popular fiction. Set in the old-world Calcutta of the Raj, these stories featuring the astute investigator and his chronicler friend Ajit are still as gripping and delightful as when they first appeared. Byomkesh’s world, peopled with wonderfully delineated characters and framed by a brilliantly captured pre-Independence urban milieu, is fascinating because of its contemporary flavor. In the first story, Byomkesh works undercover to expose an organized crime ring trafficking in drugs. In ‘The Gramophone Pin Mystery’, he must put his razor-sharp intellect to good use to unearth the pattern behind a series of bizarre roadside murders. In ‘Calamity Strikes’, the ace detective is called upon to investigate the strange and sudden death of a girl in a neighbour’s kitchen. In the next story, he has to lock horns with an old enemy who has vowed to kill him with an innocuous but deadly weapon. And in ‘Picture Imperfect’, Byomkesh Bakshi unravels a complex mystery involving a stolen group photograph, an amorous couple, and an apparently unnecessary murder. Available in English for the first time in a superb translation, these stories will captivate every lover of crime fiction, young and old alike.',
        thumbnailAddress: 'http://books.google.com/books/content?id=eNGfBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Picture Imperfect',
        wishlistDate: 0,
    },
    {
        author: 'Arun Kundnani',
        currentPage: 0,
        endDate: 0,
        googleBooksLink: 'http://books.google.co.in/books?id=UP_rnwEACAAJ&dq=the%2BMuslims%2Bare%2Bcoming&hl=&source=gbs_api',
        id: 16,
        isbn: '9781781685587',
        labels: [],
        language: 'en',
        pageCount: 256,
        position: 6,
        publishedDate: '2014-12-22',
        rating: 0,
        startDate: 0,
        state: 'READ_LATER',
        subTitle: 'Islamophobia, Extremism, and the Domestic War on Terror',
        summary:
            '"Following the killing of Osama bin Laden, polls showed that Americans were more anxious about terrorism than they were before his death. The new front in the War on Terror is the "homegrown enemy," domestic terrorists who have become the focus of sprawling counterterrorism structures of policing and surveillance in the United States, the UK, and across Europe. Based on several years of research and reportage from Dallas to Dewsbury, and written in exciting, precise prose, this is the first comprehensive critique of counter-radicalization strategies in the US and the UK. The new policies and policing campaigns have been backed by an anti-extremism industry of newly minted experts, and by examining the ideas of commentators like Martin Amis, Peter Beinart, and Christopher Caldwell, the book also looks at the way liberalism has itself been transformed by its embrace of anti-extremism"--',
        thumbnailAddress: 'http://books.google.com/books/content?id=UP_rnwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The Muslims Are Coming',
        wishlistDate: 1678244509709,
    },
    {
        author: 'Arundhati Roy',
        currentPage: 438,
        endDate: 1684934376125,
        googleBooksLink: 'https://play.google.com/store/books/details?id=5HoEDgAAQBAJ&source=gbs_api',
        id: 15,
        isbn: '9789385990977',
        labels: [],
        language: 'en',
        pageCount: 438,
        position: 0,
        publishedDate: '2018-06-26',
        rating: 0,
        startDate: 1683688243701,
        state: 'READ',
        subTitle: '',
        summary:
            "At magic hour; when the sun has gone but the light has not, armies of flying foxes unhinge themselves from the Banyan trees in the old graveyard and drift across the city like smoke . . .' So begins The Ministry of Utmost Happiness, Arundhati Roy's incredible follow-up to The God of Small Things. We meet Anjum, who used to be Aftab, who runs a guest house in an Old Delhi graveyard and gathers around her the lost, the broken and the cast out. We meet Tilo, an architect, who, although she is loved by three men, lives in a 'country of her own skin'. When Tilo claims an abandoned baby as her own, her destiny and that of Anjum become entangled as a tale that sweeps across the years and a teeming continent takes flight. . .",
        thumbnailAddress: 'http://books.google.com/books/content?id=5HoEDgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Ministry of Utmost Happiness',
        wishlistDate: 0,
    },
    {
        author: 'Nivedita Menon',
        currentPage: 0,
        endDate: 0,
        googleBooksLink: 'https://play.google.com/store/books/details?id=ISz4wRRnMvgC&source=gbs_api',
        id: 14,
        isbn: '9788184757705',
        labels: [],
        language: 'en',
        pageCount: 359,
        position: 0,
        publishedDate: '2012-12-01',
        rating: 0,
        startDate: 0,
        state: 'READ_LATER',
        subTitle: '',
        summary:
            'THE WORLD THROUGH A FEMINIST LENS For Nivedita Menon, feminism is not about a moment of final triumph over patriarchy but about the gradual transformation of the social field so decisively that old markers shift forever. From sexual harassment charges against international figures to the challenge that caste politics poses to feminism, from the ban on the veil in France to the attempt to impose skirts on international women badminton players, from queer politics to domestic servants’ unions to the Pink Chaddi campaign, Menon deftly illustrates how feminism complicates the field irrevocably. Incisive, eclectic and politically engaged, Seeing like a Feminist is a bold and wide-ranging book that reorders contemporary society.',
        thumbnailAddress: 'http://books.google.com/books/content?id=ISz4wRRnMvgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Seeing Like a Feminist',
        wishlistDate: 1681930435274,
    },
    {
        author: 'Fyodor Dostoevsky',
        currentPage: 549,
        endDate: 1678820453116,
        googleBooksLink: 'http://books.google.co.in/books?id=sYmMEAAAQBAJ&dq=crime%2Band%2Bpunishment&hl=&source=gbs_api',
        id: 13,
        isbn: '9780141192802',
        labels: [],
        language: 'en',
        pageCount: 559,
        position: 0,
        publishedDate: '2014-04-29',
        rating: 0,
        startDate: 1677778970662,
        state: 'READ',
        subTitle: '',
        summary:
            "'A truly great translation . . . This English version really is better' - A. N. Wilson, The Spectator TIMES LITERARY SUPPLEMENT BOOKS OF THE YEAR 2014 This acclaimed new translation of Dostoyevsky's 'psychological record of a crime' gives his dark masterpiece of murder and pursuit a renewed vitality, expressing its jagged, staccato urgency and fevered atmosphere as never before. Raskolnikov, a destitute and desperate former student, wanders alone through the slums of St. Petersburg, deliriously imagining himself above society's laws. But when he commits a random murder, only suffering ensues. Embarking on a dangerous game of cat and mouse with a suspicious police investigator, Raskolnikov finds the noose of his own guilt tightening around his neck. Only Sonya, a downtrodden prostitute, can offer the chance of redemption. Fyodor Dostoevsky (1821-1881) was born in Moscow and made his name in 1846 with the novella Poor Folk. He spent several years in prison in Siberia as a result of his political activities, an experience which formed the basis of The House of the Dead. In later life, he fell in love with a much younger woman and developed a ruinous passion for roulette. His subsequent great novels include Notes from Underground, Crime and Punishment, The Idiot, Demons and The Brothers Karamazov. Oliver Ready is Research Fellow in Russian Society and Culture at St Antony's College, Oxford. He is general editor of the anthology, The Ties of Blood: Russian Literature from the 21st Century (2008), and Consultant Editor for Russia, Central and Eastern Europe at the Times Literary Supplement.",
        thumbnailAddress: 'http://books.google.com/books/content?id=sYmMEAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'Penguin Classics Crime and Punishment',
        wishlistDate: 0,
    },
    {
        author: 'Friedrich Engels',
        currentPage: 22,
        endDate: 1686476679519,
        googleBooksLink: 'http://books.google.co.in/books?id=D6kWjwEACAAJ&dq=principles%2Bof%2BCommunism&hl=&source=gbs_api',
        id: 12,
        isbn: '9781519557230',
        labels: [],
        language: 'en',
        pageCount: 22,
        position: 1,
        publishedDate: '2015-11-27',
        rating: 0,
        startDate: 1685507275203,
        state: 'READ',
        subTitle: '',
        summary:
            'Friedrich Engels (November 28, 1820 - August 5, 1895) was a German industrialist, social scientist, author, political theorist, philosopher, and father of Marxist theory, working in close collaboration alongside Karl Marx. In 1845, he published The Condition of the Working Class in England, based on personal observations and research. In 1848, he produced with Marx The Communist Manifesto and later he supported Marx financially to do research and write Das Kapital. After Marx\'s death Engels edited the second and third volumes. Additionally, Engels organized Marx\'s notes on the "Theories of Surplus Value" and this was later published as the "fourth volume" of Capital. Engels is commonly known as a "ruthless party tactician", "brutal ideologue", and "master tactician" when it came to purging rivals in political organizations. However, another strand of Engels\'s personality was one of a "gregarious", "big-hearted", and "jovial man of outsize appetites", who was referred to by his son-in-law as "the great beheader of champagne bottles."',
        thumbnailAddress: 'http://books.google.com/books/content?id=D6kWjwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The Principles of Communism',
        wishlistDate: 1678244518177,
    },
    { author: 'Genrikh Nikolaevich Volkov', currentPage: 197, endDate: 1684725397422, googleBooksLink: 'http://books.google.co.in/books?id=rTFtAAAAIAAJ&dq=basics%2Bof%2BMarxist%2BLeninist%2Btheory&hl=&source=gbs_api', id: 11, isbn: '', labels: [], language: 'en', pageCount: 342, position: 0, publishedDate: '1982', rating: 0, startDate: 1681653907171, state: 'READ', subTitle: '', thumbnailAddress: 'http://books.google.com/books/content?id=rTFtAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', title: 'The Basics of Marxist-Leninist Theory', wishlistDate: 1681653903517 },
    {
        author: 'Chinua Achebe',
        currentPage: 133,
        endDate: 1681621220217,
        googleBooksLink: 'http://books.google.co.in/books?id=YTTlcWxsSFQC&dq=no%2Blonger%2Bat%2Bease&hl=&source=gbs_api',
        id: 10,
        isbn: '9780141393995',
        labels: [],
        language: 'en',
        pageCount: 133,
        position: 0,
        publishedDate: '2013-04-25',
        rating: 0,
        startDate: 1681144183295,
        state: 'READ',
        subTitle: '',
        summary:
            "Obi Okonkwo is an idealistic young man who, thanks to the privileges of an education in Britain, has now returned to Nigeria for a job in the civil service. However in his new role he finds that the way of government seems to be backhanders and corruption. Obi manages to resist the bribes that are offered to him, but when he falls in love with an unsuitable girl - to the disapproval of his parents - he sinks further into emotional and financial turmoil. The lure of easy money becomes harder to refuse, and Obi becomes caught in a trap he cannot escape. Showing a man lost in cultural limbo, and a Nigeria entering a new age of disillusionment, No Longer at Ease concludes Achebe's remarkable trilogy charting three generations of an African community under the impact of colonialism, the first two volumes of which are Things Fall Apart and Arrow of God.",
        thumbnailAddress: 'http://books.google.com/books/content?id=YTTlcWxsSFQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'No Longer at Ease',
        wishlistDate: 1680198179775,
    },
    { author: 'Anand Teltumbde', currentPage: 91, endDate: 0, googleBooksLink: 'http://books.google.co.in/books?id=tv7HtwEACAAJ&dq=republic%2Bof%2Bcaste&hl=&source=gbs_api', id: 9, isbn: '9788189059842', labels: [], language: 'en', pageCount: 822, position: 3, publishedDate: '2018', rating: 0, startDate: 0, state: 'READ_LATER', subTitle: 'Thinking Equality in the Time of Neoliberal Hindutva', title: 'Republic of Caste', wishlistDate: 1678244515693 },
    {
        author: 'Chinua Achebe',
        currentPage: 187,
        endDate: 1680197223305,
        googleBooksLink: 'https://play.google.com/store/books/details?id=tSbWMu_-D5AC&source=gbs_api',
        id: 8,
        isbn: '9780141393964',
        labels: [],
        language: 'en',
        pageCount: 187,
        position: 0,
        publishedDate: '2013-04-25',
        rating: 0,
        startDate: 1679445952226,
        state: 'READ',
        subTitle: '',
        summary:
            "Okonkwo is the greatest warrior alive, famous throughout West Africa. But when he accidentally kills a clansman, things begin to fall apart. Then Okonkwo returns from exile to find missionaries and colonial governors have arrived in the village. With his world thrown radically off-balance he can only hurtle towards tragedy. Chinua Achebe's stark novel reshaped both African and world literature. This arresting parable of a proud but powerless man witnessing the ruin of his people begins Achebe's landmark trilogy of works chronicling the fate of one African community, continued in Arrow of God and No Longer at Ease.",
        thumbnailAddress: 'https://books.google.com/books/content?id=tSbWMu_-D5AC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Things Fall Apart',
        wishlistDate: 0,
    },
    {
        author: 'Sally Rooney',
        currentPage: 140,
        endDate: 1679445916474,
        googleBooksLink: 'http://books.google.co.in/books?id=cjmREAAAQBAJ&dq=normal%2Bpeople&hl=&source=gbs_api',
        id: 7,
        isbn: '9781984822185',
        labels: [],
        language: 'en',
        pageCount: 140,
        position: 0,
        publishedDate: '2020-02-18',
        rating: 0,
        startDate: 0,
        state: 'READ',
        subTitle: 'A Novel',
        summary:
            'NOW AN EMMY-NOMINATED HULU ORIGINAL SERIES • NEW YORK TIMES BESTSELLER • “A stunning novel about the transformative power of relationships” (People) from the author of Conversations with Friends, “a master of the literary page-turner” (J. Courtney Sullivan). ONE OF THE TEN BEST NOVELS OF THE DECADE—Entertainment Weekly TEN BEST BOOKS OF THE YEAR—People, Slate, The New York Public Library, Harvard Crimson AND BEST BOOKS OF THE YEAR—The New York Times, The New York Times Book Review, O: The Oprah Magazine, Time, NPR, The Washington Post, Vogue, Esquire, Glamour, Elle, Marie Claire, Vox, The Paris Review, Good Housekeeping, Town & Country Connell and Marianne grew up in the same small town, but the similarities end there. At school, Connell is popular and well liked, while Marianne is a loner. But when the two strike up a conversation—awkward but electrifying—something life changing begins. A year later, they’re both studying at Trinity College in Dublin. Marianne has found her feet in a new social world while Connell hangs at the sidelines, shy and uncertain. Throughout their years at university, Marianne and Connell circle one another, straying toward other people and possibilities but always magnetically, irresistibly drawn back together. And as she veers into self-destruction and he begins to search for meaning elsewhere, each must confront how far they are willing to go to save the other. Normal People is the story of mutual fascination, friendship and love. It takes us from that first conversation to the years beyond, in the company of two people who try to stay apart but find that they can’t. Praise for Normal People “[A] novel that demands to be read compulsively, in one sitting.”—The Washington Post “Arguably the buzziest novel of the season, Sally Rooney’s elegant sophomore effort . . . is a worthy successor to Conversations with Friends. Here, again, she unflinchingly explores class dynamics and young love with wit and nuance.”—The Wall Street Journal “[Rooney] has been hailed as the first great millennial novelist for her stories of love and late capitalism. . . . [She writes] some of the best dialogue I’ve read.”—The New Yorker',
        thumbnailAddress: 'http://books.google.com/books/content?id=cjmREAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'Normal People',
        wishlistDate: 0,
    },
    {
        author: 'Vladimir Ilʹich Lenin',
        currentPage: 125,
        endDate: 0,
        googleBooksLink: 'http://books.google.co.in/books?id=15BEAQAAMAAJ&dq=state%2Band%2Bthe%2Brevolution&hl=&source=gbs_api',
        id: 6,
        isbn: '',
        labels: [],
        language: 'en',
        pageCount: 420,
        position: 2,
        publishedDate: '1919',
        rating: 0,
        startDate: 0,
        state: 'READ_LATER',
        subTitle: 'Marxist Teaching on the State and the Task of the Proletariat in the Revolution',
        thumbnailAddress: 'http://books.google.com/books/content?id=15BEAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'The State and Revolution',
        wishlistDate: 1681144684599,
    },
    {
        author: 'Chinua Achebe',
        currentPage: 222,
        endDate: 1681144175496,
        googleBooksLink: 'https://play.google.com/store/books/details?id=BlffwGz4V5YC&source=gbs_api',
        id: 5,
        isbn: '9780141393988',
        labels: [],
        language: 'en',
        pageCount: 222,
        position: 0,
        publishedDate: '2023-04-10',
        rating: 0,
        startDate: 1680589800000,
        state: 'READ',
        subTitle: '',
        summary:
            "Ezeulu, headstrong chief priest of the god Ulu, is worshipped by the six villages of Umuaro. But he is beginning to find his authority increasingly under threat - from his rivals in the tribe, from those in the white government and even from his own family. Yet he still feels he must be untouchable - surely he is an arrow in the bow of his God? Armed with this belief, he is prepared to lead his people, even if it means destruction and annihilation. Yet the people will not be so easily dominated. Spare and powerful, Arrow of God is an unforgettable portrayal of the loss of faith, and the struggle between tradition and change. Continuing the epic saga of the community in Things Fall Apart, it is the second volume of Achebe's African trilogy, and is followed by No Longer at Ease.",
        thumbnailAddress: 'http://books.google.com/books/content?id=BlffwGz4V5YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Arrow of God',
        wishlistDate: 1680589800000,
    },
    {
        author: 'Paulo Freire',
        currentPage: 72,
        endDate: 0,
        googleBooksLink: 'http://books.google.co.in/books?id=r51MDwAAQBAJ&dq=9780241301111&hl=&source=gbs_api',
        id: 4,
        isbn: '9781501314148',
        labels: [],
        language: 'en',
        pageCount: 374,
        position: 3,
        publishedDate: '2018-03-22',
        rating: 0,
        startDate: 0,
        state: 'READ_LATER',
        subTitle: '50th Anniversary Edition',
        summary:
            "First published in Portuguese in 1968, Pedagogy of the Oppressed was translated and published in English in 1970. Paulo Freire's work has helped to empower countless people throughout the world and has taken on special urgency in the United States and Western Europe, where the creation of a permanent underclass among the underprivileged and minorities in cities and urban centers is ongoing. This 50th anniversary edition includes an updated introduction by Donaldo Macedo, a new afterword by Ira Shor and interviews with Marina Aparicio Barber�n, Noam Chomsky, Ram�n Flecha, Gustavo Fischman, Ronald David Glass, Valerie Kinloch, Peter Mayo, Peter McLaren and Margo Okazawa-Rey to inspire a new generation of educators, students, and general readers for years to come.",
        thumbnailAddress: 'http://books.google.com/books/content?id=r51MDwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
        title: 'Pedagogy of the Oppressed',
        wishlistDate: 1680138158149,
    },
    {
        author: 'Michael Parenti',
        currentPage: 0,
        endDate: 0,
        googleBooksLink: 'https://play.google.com/store/books/details?id=dEX8DwAAQBAJ&source=gbs_api',
        id: 3,
        isbn: '9780872868199',
        labels: [],
        language: 'en',
        pageCount: 354,
        position: 1,
        publishedDate: '2020-09-09',
        rating: 0,
        startDate: 0,
        state: 'READ_LATER',
        subTitle: 'Rational Fascism and the Overthrow of Communism',
        summary:
            'A bold and entertaining exploration of the epic struggles of yesterday and today. Blackshirts & Reds explores some of the big issues of our time: fascism, capitalism, communism, revolution, democracy, and ecology. These terms are often bandied about, but seldom explored in the original and exciting way that has become Michael Parenti\'s trademark. Parenti shows how "rational fascism" renders service to capitalism, how corporate power undermines democracy, and how revolutions are a mass empowerment against the forces of exploitative privilege. He also maps out the external and internal forces that destroyed communism, and the disastrous impact of the "free-market" victory on eastern Europe and the former Soviet Union. He affirms the relevance of taboo ideologies like Marxism, demonstrating the importance of class analysis in understanding political realities and dealing with the ongoing collision between ecology and global corporatism. Written with lucid and compelling style, this book goes beyond truncated modes of thought, inviting us to entertain iconoclastic views, and to ask why things are as they are. "A penetrating and persuasive writer with an astonishing array of documentation to implement his attacks." —The Catholic Journalist "By portraying the struggle between fascism and Communism in this century as a single conflict, and not a series of discrete encounters, between the insatiable need for new capital on the one hand and the survival of a system under siege on the other, Parenti defines fascism as the weapon of capitalism, not simply an extreme form of it. Fascism is not an aberration, he points out, but a \'rational\' and integral component of the system."—Stan Goff, author of Full Spectrum Disorder: The Military in the New American Century Michael Parenti, PhD Yale, is an internationally known author and lecturer. He is one of the nation\'s leading progressive political analysts. Author of over 275 published articles and twenty books, his writings are published in popular periodicals, scholarly journals, and his op-ed pieces have been in leading newspapers such as The New York Times and The Los Angeles Times. His informative and entertaining books and talks have reached a wide range of audiences in North America and abroad.',
        thumbnailAddress: 'http://books.google.com/books/content?id=dEX8DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Blackshirts and Reds',
        wishlistDate: 1680138161289,
    },
    {
        author: 'Agatha Christie',
        currentPage: 320,
        endDate: 1646807400000,
        googleBooksLink: 'https://play.google.com/store/books/details?id=ywp6OPxUHLMC&source=gbs_api',
        id: 2,
        isbn: '9780007422531',
        labels: [],
        language: 'en',
        pageCount: 320,
        position: 0,
        publishedDate: '2010-10-14',
        rating: 0,
        startDate: 1645606575984,
        state: 'READ',
        subTitle: '',
        summary: 'Agatha Christie’s ingenious murder mystery thriller, reissued with a striking cover designed to appeal to the latest generation of Agatha Christie fans and book lovers.',
        thumbnailAddress: 'http://books.google.com/books/content?id=ywp6OPxUHLMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Murder Is Easy',
        wishlistDate: 0,
    },
    {
        author: 'Satyajit Ray, Satyajit',
        currentPage: 276,
        endDate: 1643961890730,
        googleBooksLink: 'http://books.google.co.in/books?id=H0qKROLb89AC&dq=indigo%2Bsatyajit%2Bray&hl=&source=gbs_api',
        id: 1,
        isbn: '9780143068099',
        labels: [],
        language: 'en',
        pageCount: 276,
        position: 0,
        publishedDate: '2020-04-20',
        rating: 0,
        startDate: 1643265000000,
        state: 'READ',
        subTitle: '',
        summary:
            "Indigo is a collection of stories about the supernatural, the peculiar and the inexplicable from Satyajit Ray, one of the best-loved writers of our times. There are tales here of dark horror, fantasy and adventure along with heart-warmingly funny stories about ordinary people in extraordinary situations. In 'Big Bill' Tulsi Babu picks up a newly-hatched chick from a forest and brings it home only to find it growing bigger and fiercer by the day; in 'Khagam' a man kills a sadhu's deadly pet snake and invites a curse which brings about horrifying changes in his body; and in the title story, a young executive resting in an old abandoned bungalow for a night, finds himself caught up in a chilling sequence of events which occurred more than a century ago. Also included here is 'The Magical Mystery', a brand new Feluda story discovered amongst Ray's papers after his death, and several tales featuring Uncle Tarini, the master storyteller who appears in translation for the first time. From Mr. Shasmal, who is visited one night by all the creatures he has ever killed, to Ashamanja Babu, who does not know what to do when his pet dog suddenly begins to laugh, the unforgettable characters in these stories surprise, shock and entertain us in equal measure. Indigo is a veritable treasure trove especially for those who like a taste of the unusual in a short story and an unexpected twist at the end. Translated from the Bengali by the author and Gopa Majumdar.",
        thumbnailAddress: 'http://books.google.com/books/content?id=H0qKROLb89AC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Indigo',
        wishlistDate: 0,
    },
    {
        author: 'Angela Y. Davis',
        currentPage: 0,
        endDate: 0,
        googleBooksLink: 'https://play.google.com/store/books/details?id=_wZ35GI4itgC&source=gbs_api',
        id: 0,
        isbn: '9781609801045',
        labels: [],
        language: 'en',
        pageCount: 128,
        position: 0,
        publishedDate: '2011-01-04',
        rating: 0,
        startDate: 0,
        state: 'READ_LATER',
        subTitle: '',
        summary:
            'With her characteristic brilliance, grace and radical audacity, Angela Y. Davis has put the case for the latest abolition movement in American life: the abolition of the prison. As she quite correctly notes, American life is replete with abolition movements, and when they were engaged in these struggles, their chances of success seemed almost unthinkable. For generations of Americans, the abolition of slavery was sheerest illusion. Similarly,the entrenched system of racial segregation seemed to last forever, and generations lived in the midst of the practice, with few predicting its passage from custom. The brutal, exploitative (dare one say lucrative?) convict-lease system that succeeded formal slavery reaped millions to southern jurisdictions (and untold miseries for tens of thousands of men, and women). Few predicted its passing from the American penal landscape. Davis expertly argues how social movements transformed these social, political and cultural institutions, and made such practices untenable. In Are Prisons Obsolete?, Professor Davis seeks to illustrate that the time for the prison is approaching an end. She argues forthrightly for "decarceration", and argues for the transformation of the society as a whole.',
        thumbnailAddress: 'http://books.google.com/books/content?id=_wZ35GI4itgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        title: 'Are Prisons Obsolete?',
        wishlistDate: 1628185902961,
    },
];
